baseurl = "https://www.nourako.com/"
title = "nourako"
theme = "hugo-theme-console"
languageCode = "en-us"
enableEmoji = true 

ignoreLogs = ["warning-goldmark-raw-html"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  # Social links (replacing deprecated .Site.Social)
  [[params.social]]
  name = "Instagram"
  url = "https://www.instagram.com/nourako999/"

  [[params.social]]
  name = "GitHub"
  url = "https://github.com/nourako"

  # Author information (replacing deprecated .Site.Authors)
  author = "Nourako"

  [[params.navlinks]]
  name = "works/"
  url = "works/"

  [[params.navlinks]]
  name = "about/"
  url = "about/"
